from pathlib import Path
import ast,re,json
ROOT=Path(__file__).resolve().parents[1]
s=(ROOT/'main.py').read_text(encoding='utf-8')
checks={}
def ck(name,cond): checks[name]=bool(cond); print(('PASS ' if cond else 'FAIL ')+name)
try: ast.parse(s); ck('main_ast',True)
except Exception: ck('main_ast',False)
ck('identity','Anatomic Pass 44' in s and 'Combo Composer' in s)
ck('runtime_flag','--pass44-smoke' in s and 'ANATOMIC_PASS44_SMOKE' in s)
ck('proof_flag','--pass44-proof' in s and 'ANATOMIC_PASS44_SCREENSHOT' in s)
ck('combo_constants','COMBO_SLOT_COUNT = 9' in s and 'COMBO_MAX_MOVES = 6' in s and 'COMBO_MIN_MOVES = 2' in s)
ck('schema_v3','anatomic.melee_slots.v3' in s and 'anatomic.melee_combo.v1' in s)
ck('recording_schema_preserved','anatomic.melee_recording.v2' in s and "('anatomic.melee_recording.v1','anatomic.melee_recording.v2')" in s)
ck('combo_reference_schema',"'sequence':list(meta['sequence'])" in s and "'samples'" not in s[s.find('def _serialize_melee_combo'):s.find('def _deserialize_melee_combo')])
ck('combo_persistence',"'combos':{str(k):self._serialize_melee_combo" in s and "'active_combo_slot':int(self.active_combo_slot)" in s)
ck('velocity_bridge','def _combo_hermite' in s and 'COMBO_TRANSITION_TANGENT_SCALE' in s and 'def _combo_sample_velocity' in s)
ck('bridge_bounds','COMBO_TRANSITION_MIN' in s and 'COMBO_TRANSITION_MAX' in s and 'def _combo_transition_duration' in s)
ck('angle_aware_bridge','_combo_angle_distance' in s and 'COMBO_TRANSITION_ANGLE_RATE' in s)
ck('non_damage_windows','combo_windows' in s and 'transition_ranges' in s and 'def _combo_window_at' in s)
ck('previous_frame_gate',"previous_time<float(w['start'])" in s)
ck('per_move_dynamics',"float(w['charge'])" in s and "float(w['travel'])" in s and "combo_hit_counts" in s)
ck('per_move_contact_cap',"count<5" in s and 'combo_last_hit_times' in s)
ck('full_motion_source','self._effective_melee_recording(raw)' in s and "float(q['t'])/speed" in s)
ck('body_solver_preserved','def _update_melee_body_solver' in s and 'BODY_SOLVER_LOOKAHEAD' in s)
ck('motion_dynamics_preserved','SWORD_DYN_REFERENCE_SPEED' in s and 'def _sword_motion_dynamics' in s)
ck('distortion_preserved','SWORD_DISTORTION_LIFE' in s and 'sword_distortion_history' in s)
ck('dismember_preserved','SWORD_MIN_SEVER_CHARGE' in s and 'detached_limbs' in s)
ck('audio_preserved',"'sword_move'" in s and "'sword_impact'" in s)
ck('forge_preserved','def _build_motion_forge_ui' in s and '--pass43-smoke' in s)
ck('f3_modal',"self.accept('f3', self.toggle_combo_composer)" in s and 'def toggle_combo_composer' in s)
ck('modal_hides_hud','self.combo_composer.show()' in s and 'self.cross.hide(); self.status.hide(); self.hint.hide()' in s)
ck('modal_hides_viewmodel','self.melee_root.hide()' in s and 'self.melee_root.show()' in s)
ck('clickable_sources',"text=f'+{i}'" in s and 'command=self._combo_append_move' in s)
ck('clickable_banks',"text=f'C{i}'" in s and 'command=self._combo_select_slot' in s)
ck('preview','def _combo_preview' in s and "source='composer_preview'" in s)
ck('armed_combo',"self.accept('0', self._play_active_combo)" in s and 'def _play_active_combo' in s)
ck('cycle_combo',"self.accept('tab', self._cycle_active_combo)" in s and 'def _cycle_active_combo' in s)
ck('number_append','if self.combo_composer_visible:' in s[s.find('def _number_key'):s.find('def _melee_angle_lerp')] and 'self._combo_append_move(slot)' in s)
ck('max_moves_enforced','len(seq)>=COMBO_MAX_MOVES' in s)
ck('source_immutability_smoke','immutable=(before==after)' in s and 'transition_damage' in s)
ck('local_independence_smoke','self.player_pos=Vec3(7.0,-4.0,0.0)' in s and 'local_ok=' in s)
ck('help_controls','F3      Combo Composer' in s and '0       play armed combo' in s and 'TAB     cycle armed combos' in s)
failed=[k for k,v in checks.items() if not v]
out={'schema':'anatomic.pass44.combo_composer.contract.v1','result':'PASS' if not failed else 'FAIL','passed':len(checks)-len(failed),'total':len(checks),'checks':checks}
(ROOT/'validation_pass44_contract.json').write_text(json.dumps(out,indent=2))
print(f'ANATOMIC_PASS44_COMBO_COMPOSER_CONTRACT={out["passed"]}/{out["total"]} {out["result"]}')
if failed:
    print('FAILED='+','.join(failed)); raise SystemExit(1)
