from pathlib import Path
import ast, json
root = Path(__file__).resolve().parents[1]
source = (root / 'main.py').read_text(encoding='utf-8')
ast.parse(source)
texture_dir = root / 'textures'
ambience_dir = root / 'audio' / 'ambience'
checks = {
    'panda_version_pinned': 'panda3d==1.10.16' in (root / 'requirements.txt').read_text(),
    'pass59_identity': 'Pass 59 — AR Coverage Continuity + Tree Removal' in source,
    'esc_pause_bound': 'self.accept("escape",self._toggle_pause)' in source,
    'cursor_hidden': 'setCursorHidden(True)' in source,
    'dt_movement': 'globalClock.getDt()' in source,
    'ar_camera_mask': 'self.ar_camera.node().setCameraMask(AR_CAMERA_MASK)' in source,
    'ar_layer_hidden_from_normal_camera': 'self.utopia_root.hide(NORMAL_CAMERA_MASK)' in source,
    'lens_controls': 'self.accept("mouse3",self._lens_hold,[True])' in source and 'self.accept("l",self._toggle_lens)' in source and 'self.accept("v",self._cycle_visor_mode)' in source,
    'ar_dormant_when_off': 'self.ar_buffer.setActive(False)' in source,
    'visor_mode_order': 'VISOR_MODE_ORDER = ("horizontal", "vertical", "fullscreen")' in source,
    'visor_mode_config': '"horizontal": {"center": (0.50, 0.52), "half_size": (0.506, 0.195)' in source and '"vertical": {"center": (0.50, 0.50), "half_size": (0.195, 0.506)' in source and '"fullscreen": {"center": (0.50, 0.50), "half_size": (0.506, 0.506)' in source,
    'visor_shader_uniforms': 'uniform vec2 lens_half_size;' in source and 'uniform float lens_corner;' in source and 'sdRoundedBox' in source,
    'visor_shader_inputs': 'self.ar_card.setShaderInput("lens_center", config["center"])' in source and 'self.ar_card.setShaderInput("lens_half_size", config["half_size"])' in source and 'self.ar_card.setShaderInput("lens_corner", config["corner"])' in source,
    'visor_apply_helper': 'def _apply_visor_mode' in source,
    'visor_cycle_helper': 'def _cycle_visor_mode' in source,
    'visor_hud_labels': 'UTOPIA // {label} VISOR ACTIVE' in source,
    'visor_cli_mode': 'ap.add_argument("--visor-mode"' in source,
    'visor_smoke_support': 'VISOR_SMOKE_PASS modes=horizontal,vertical,fullscreen' in source,
    'physical_day_length': 'PHYSICAL_DAY_LENGTH_SECONDS = 2160.0' in source,
    'split_time_state': 'self.physical_time_hours' in source and 'self.ar_time_hours' in source,
    'physical_time_profile': 'def _physical_time_profile' in source,
    'ar_time_profile': 'def _ar_time_profile' in source,
    'time_visual_application': 'def _apply_time_visuals' in source and 'self.sun_light.setColor' in source and 'self.ar_card.setShaderInput("ar_time_tint"' in source,
    'pause_time_menu': 'WORLD   {self._format_clock(self.physical_time_hours)}' in source and 'AR      {self._format_clock(self.ar_time_hours)}' in source,
    'arrow_hour_controls': 'self.accept("arrow_up",self._adjust_ar_time,[1.0])' in source and 'self.accept("arrow_down",self._adjust_ar_time,[-1.0])' in source,
    'arrow_fine_controls': 'self.accept("arrow_left",self._adjust_ar_time,[-AR_FINE_TIME_STEP_HOURS])' in source and 'self.accept("arrow_right",self._adjust_ar_time,[AR_FINE_TIME_STEP_HOURS])' in source,
    'menu_only_time_adjustment': 'if not self.paused or self.pause_panel_mode != "pause":' in source,
    'time_smoke_support': 'TIME_SMOKE_PASS' in source and 'args.time_smoke' in source,
    'time_cli_controls': 'ap.add_argument("--physical-time"' in source and 'ap.add_argument("--ar-time"' in source and 'ap.add_argument("--freeze-time"' in source,
    'pause_menu_proof_support': 'ap.add_argument("--pause-menu-shot"' in source and 'capture_pause_menu' in source,
    'time_hud_contrast': 'def _update_hud_contrast' in source,
    'weather_order': 'WEATHER_ORDER = ("clear", "overcast", "rain", "storm", "post_rain")' in source,
    'weather_profiles': 'WEATHER_PROFILES =' in source and '"storm":' in source and '"post_rain":' in source,
    'weather_cycle_durations': 'WEATHER_DURATIONS_SECONDS' in source and 'WEATHER_TRANSITION_SECONDS = 10.0' in source,
    'weather_state_machine': 'def _cycle_weather_state' in source and 'def _update_weather_system' in source,
    'weather_physical_only_mask': 'self.weather_root.hide(AR_CAMERA_MASK)' in source,
    'weather_rain_batches': 'rain_batch_' in source and 'rain_streaks' in source,
    'weather_pause_menu': 'self._weather_label()' in source and 'PAUSED // UTOPIA' in source,
    'weather_smoke_support': 'WEATHER_SMOKE_PASS' in source and 'args.weather_smoke' in source,
    'weather_cli_controls': 'ap.add_argument("--weather-state"' in source and 'ap.add_argument("--freeze-weather"' in source,
    'weather_no_ar_state': 'ar_weather' not in source,
    'movement_constants': 'WALK_SPEED =' in source and 'SPRINT_SPEED =' in source and 'JUMP_SPEED =' in source and 'GRAVITY =' in source,
    'sprint_applies_to_vector_motion': 'SWIM_SPEED if self.in_water else (SPRINT_SPEED if self.key_state["sprint"] else WALK_SPEED)' in source,
    'jump_uses_constant': 'self.vertical_velocity=JUMP_SPEED' in source,
    'gravity_uses_constant': 'self.vertical_velocity -= GRAVITY*dt' in source,
    'control_smoke_diagonal': 'self.key_state["right"]=True' in source and 'dx={float(delta.x):.3f}' in source and 'dy={float(delta.y):.3f}' in source,
    'control_smoke_lens_proof': 'self._control_smoke_saw_lens' in source and 'self._lens_hold(True)' in source,
    'district_theme_table': 'DISTRICT_THEMES =' in source,
    'pedestrian_texture_table': 'PEDESTRIAN_TEXTURES =' in source,
    'texture_prepare_helper': 'def _prepare_texture' in source and 'setAnisotropicDegree(16)' in source,
    'overlay_stabilization_helper': 'def _stabilize_overlay' in source and 'setDepthOffset' in source,
    'spec_variant_helper': 'def _spec_variant' in source,
    'spec_scalar_helper': 'def _spec_scalar' in source,
    'hero_signature_helper': 'def _hero_signature_key' in source and 'def _add_box_hero_signature' in source and 'def _add_cylinder_hero_signature' in source,
    'wall_plinth_present': '_plinth' in source,
    'wall_cap_present': '_cap' in source,
    'wall_pier_present': '_pier' in source,
    'wall_fin_present': '_fin_' in source,
    'pedestrian_texture_loader': 'def _load_pedestrian_textures' in source,
    'textured_disc_geom': 'def make_textured_disc_geom' in source,
    'textured_annulus_sector': 'def make_textured_annulus_sector' in source,
    'textured_promenade_box': 'def _promenade_textured_box' in source,
    'textured_promenade_sector': 'def _promenade_textured_sector' in source,
    'textured_walkway_stats': '"textured_walkways": 0' in source,
    'pedestrian_surface_layer': 'def _add_pedestrian_surface_layer' in source,
    'no_traffic_language_code': 'lane_arrow' not in source and 'traffic_light' not in source and 'vehicle_route' not in source,
    'no_floating_route_ring': 'ar_transit_ring' not in source,
    'no_sky_lattice': 'sky_latitude_' not in source and 'sky_orb_' not in source,
    'living_facade_registry': 'self.ar_activity_nodes = []' in source,
    'activity_update': 'def _update_ar_activity' in source,
    'closed_door_state': '_door_recess' in source and '_door_glow' in source,
    'qa_walls_added': '"walls":' in source and '"lens_walls"' in source,
    'coverage_stats_present': '"coverage_roof_crowns": 0' in source and '"coverage_wall_pieces": 0' in source and '"coverage_gate_pieces": 0' in source and '"coverage_transit_pieces": 0' in source and '"coverage_overlook_pieces": 0' in source,
    'surface_detail_stats_present': '"detail_wall_surfaces": 0' in source and '"detail_gate_surfaces": 0' in source and '"detail_transit_surfaces": 0' in source and '"detail_roof_surfaces": 0' in source and '"detail_overlook_surfaces": 0' in source and '"detail_sidewalk_surfaces": 0' in source and '"detail_ground_fields": 0' in source,
    'surface_detail_color_helper': 'def _detail_color' in source,
    'wall_structural_bays': 'detail_panel' in source and 'detail_tall' in source and 'detail_center' in source,
    'gate_service_bays': 'bridge_{angle}_bay_' in source and 'bridge_{angle}_barrier_cap_' in source,
    'transit_fascia_detail': 'transit_fascia_' in source and 'transit_support_collar_' in source,
    'roof_cross_brace_detail': '_roof_detail_a' in source and '_roof_detail_b' in source and '_roof_detail_hub' in source,
    'overlook_post_detail': 'overlook_post_' in source and 'overlook_back_post_' in source,
    'sidewalk_surface_coverage': 'sidewalk_ring_' in source and 'promenade_sidewalk_' in source,
    'gate_return_detail': 'gate_return_' in source and 'gate_return_band_' in source,
    'district_ground_fields': 'district_ground_' in source and '78.0' in source,
    'overlook_surface_alignment_fix': 'overlook_x,overlook_y,_=polar(452,180,0.205)' in source or 'overlook_x,overlook_y,_=polar(452,180,0.25)' in source,
    'outward_wall_detail': 'outer_panel' in source and 'outer_rib' in source and 'outer_header' in source,
    'clean_coverage_helper': 'def _coverage_box' in source and 'def _coverage_color' in source,
    'wall_coverage_builder': 'def _add_wall_ar_coverage' in source,
    'gate_coverage_builder': 'def _add_gate_ar_coverage' in source,
    'transit_coverage_builder': 'def _add_transit_ar_coverage' in source,
    'overlook_coverage_builder': 'def _add_overlook_ar_coverage' in source,
    'coverage_qa_states': '"gate":' in source and '"transit":' in source and '"roof":' in source and 'lens_gate' in source and 'lens_transit' in source and 'lens_roof' in source,
    'environment_stats_present': '"physical_sky": 0' in source and '"ar_sky": 0' in source and '"ar_water": 0' in source and '"shore_shelves": 0' in source,
    'sky_dome_helper': 'def make_sky_dome_geom' in source,
    'physical_sky_builder': 'physical_sky = make_sky_dome_geom' in source and 'physical_sky.hide(AR_CAMERA_MASK)' in source,
    'ar_environment_builder': 'def _build_ar_environment' in source and 'utopia_ar_environment' in source,
    'ar_water_shader': 'ar_water_surface' in source and 'uniform float env_time' in source,
    'coastal_shelves': 'ar_coastal_shelf_' in source,
    'environment_update': 'self.ar_water_surface.setShaderInput("env_time", self.environment_time)' in source,
    'environment_qa_states': '"environment":' in source and '"water":' in source and '"sky":' in source and 'lens_environment' in source and 'lens_water' in source and 'lens_sky' in source,
    'coverage_not_wallpaper_textured': 'def _coverage_textured_box' not in source,
    'promenade_qa_state': '"promenade":((0,-360,6.0)' in source and 'lens_promenade' in source,
    'ambience_json_import': 'import json' in source,
    'ambience_loader': 'def _load_dynamic_ambience' in source,
    'ambience_update': 'def _update_dynamic_ambience' in source,
    'ambience_radial_outer': 'shape == "radial_outer"' in source,
    'ambience_point_zone': 'shape == "point"' in source,
    'ambience_smoothing': 'math.exp(-max(0.0,float(dt))/smoothing)' in source,
    'ambience_smoke_support': 'AMBIENCE_SMOKE_PASS' in source and 'args.ambience_smoke' in source,
    'ambience_cardinal_symmetry_test': 'cardinal_symmetry=1' in source and 'wall_values=[' in source,
    'ambience_fade_up_down_test': 'fade_up=1 fade_down=1' in source and 'raised_current' in source and 'lowered_current' in source,
    'ambience_no_audio_flag': 'args.offscreen or args.no_audio' in source,
    'ambience_replaceable_config': 'ambience_zones.json' in source,
    'utopia_system_stats': 'self.utopia_system_stats = {' in source and '"systems": 0' in source,
    'utopia_system_builder': 'def _build_utopia_project_systems' in source,
    'utopia_archive_node': 'civic_archive_station_nine_access' in source and 'def _build_archive_station_access' in source,
    'utopia_dream_node': 'somnology_dream_catcher_node' in source and 'def _build_dream_catcher_node' in source and 'range(7)' in source,
    'utopia_eco_node': 'eco_climate_control_node' in source and 'eco_control_ring_' in source,
    'utopia_harbor_node': 'harbor_logistics_beacon' in source and 'def _build_harbor_logistics_beacon' in source,
    'utopia_industry_node': 'industry_fabrication_gantry' in source and 'def _build_industry_fabrication_gantry' in source,
    'utopia_systems_ar_only': 'self._build_utopia_project_systems()' in source and 'self.utopia_root.hide(NORMAL_CAMERA_MASK)' in source,
    'utopia_systems_smoke_support': 'UTOPIA_SYSTEMS_SMOKE_PASS' in source and 'args.utopia_systems_smoke' in source,
    'utopia_systems_qa_states': '"utopia_archive":' in source and '"utopia_dream":' in source and '"utopia_eco":' in source and '"utopia_harbor":' in source and '"utopia_industry":' in source,
    'north_building_texture_exists': (texture_dir / 'north_civic_lattice.png').exists(),
    'east_building_texture_exists': (texture_dir / 'east_innovation_pulse.png').exists(),
    'south_building_texture_exists': (texture_dir / 'south_garden_flow.png').exists(),
    'west_building_texture_exists': (texture_dir / 'west_foundry_signal.png').exists(),
    'core_building_texture_exists': (texture_dir / 'core_unity_signal.png').exists(),
    'north_paving_texture_exists': (texture_dir / 'north_pedestrian_pavers.png').exists(),
    'east_paving_texture_exists': (texture_dir / 'east_pedestrian_pulse.png').exists(),
    'south_paving_texture_exists': (texture_dir / 'south_pedestrian_flow.png').exists(),
    'west_paving_texture_exists': (texture_dir / 'west_pedestrian_foundry.png').exists(),
    'core_paving_texture_exists': (texture_dir / 'core_pedestrian_forum.png').exists(),
    'ambience_config_exists': (ambience_dir / 'ambience_zones.json').exists(),
    'ocean_loop_exists': (ambience_dir / 'ocean_loop.wav').exists(),
    'ambience_asset_guide_exists': (ambience_dir / 'README.md').exists(),
    'modal_smoke_support': 'MODAL_SMOKE_PASS' in source and 'args.modal_smoke' in source,
    'collision_smoke_support': 'COLLISION_SMOKE_PASS' in source and 'args.collision_smoke' in source,
    'pause_clears_movement': 'def _clear_movement_keys' in source and 'self._clear_movement_keys()' in source,
    'paused_tour_spawn_blocked': 'if getattr(self,"paused",False):' in source,
    'help_stays_modal': 'if self.pause_panel_mode == "help":' in source and 'self.pause_panel_mode = "pause"' in source,
    'ambience_zone_normalizer': 'def _normalize_ambience_zone' in source,
    'ambience_project_relative_guard': 'asset_must_be_project_relative' in source and 'asset_outside_project' in source,
    'ambience_numeric_sanitizer': 'def _ambience_float' in source,
    'ambience_loop_reconciliation': 'sound.status() != AudioSound.PLAYING' in source and 'reconcile_elapsed' in source,
    'null_audio_reconcile_guard': 'NullAudioManager' in source and 'reconcile_enabled' in source,
    'no_silent_audio_exception_swallow': 'except Exception:\n                    pass' not in source,
    'help_menu_proof_support': 'ap.add_argument("--help-menu-shot"' in source and 'capture_help_menu' in source,
    'point_zone_runtime_test': 'point_zone=1' in source and 'qa_point' in source,
    'asset_audit_tool_exists': (root / 'tools' / 'audit_assets.py').exists(),
    'utopia_system_activity_registry': 'self.utopia_system_activity = []' in source and 'def _register_utopia_system_activity' in source,
    'utopia_system_activity_update': 'def _update_utopia_system_activity' in source and 'self._update_utopia_system_activity()' in source,
    'utopia_all_five_systems_active': all(token in source for token in ('\"archive\",\"archive_record\"','\"dream\",\"dream_pod\"','\"eco\",\"eco_sensor\"','\"harbor\",\"harbor_light\"','\"industry\",\"fab_head\"')),
    'utopia_fabrication_motion': 'motion_y=1.35' in source and 'motion_z=0.42' in source,
    'utopia_activity_smoke_contract': 'motion_delta>0.05' in source and 'light_delta>0.02' in source,
    'ar_reflective_material_shader': 'self.ar_reflective_shader = Shader.make' in source and 'reflection_strength' in source,
    'ar_pattern_neon_shader': 'self.ar_pattern_shader = Shader.make' in source and 'neon_gain' in source and 'neonMask' in source,
    'ar_material_stats': 'reflective_solids' in source and 'neon_patterns' in source,
    'ar_pattern_post_glow': 'uniform vec2 ar_texel_size;' in source and 'samples*glow*0.11' in source,
    'ar_material_smoke_thresholds': 'reflective_solids"] < 500' in source and 'neon_patterns"] < 150' in source,
    'ar_neon_spill_registry': 'self.ar_neon_spill_sources = []' in source and 'def _register_neon_spill_source' in source,
    'ar_neon_spill_shader': 'oneSpill' in source and 'spill_pos_radius4' in source and 'spill_color_intensity4' in source,
    'ar_neon_spill_five_sources': source.count('_register_neon_spill_source(root,') == 5,
    'ar_neon_spill_runtime_update': 'def _update_neon_spill_inputs' in source and 'self._update_neon_spill_inputs()' in source,
    'ar_neon_spill_smoke_contract': 'spill_delta>0.005' in source and 'spill_sources' in source,
    'natural_outer_palette': all(token in source for token in ('outer_grass','outer_dirt','outer_shore')),
    'outer_land_builder': 'earthlike_outer_world' in source and 'outer_grass_mainland' in source and 'outer_dirt_shore' in source,
    'outer_land_bridge_alignment': '688.0, 724.0' in source and '754.0, 1490.0' in source,
    'ar_outer_natural_sky': 'ar_natural_outer_sky' in source and 'outer_mix = self._smoothstep01((radius - 500.0) / 90.0)' in source,
    'ar_geographic_sky_authority': 'self.ar_natural_sky.setColorScale(sky[0], sky[1], sky[2], outer_mix)' in source and '1.0 - outer_mix' in source,
    'earthlike_physical_sky': '(0.72,0.84,0.94,1.0)' in source and '(0.10,0.36,0.72,1.0)' in source,
    'celestial_builder': 'def _build_celestial_system' in source and 'physical_moon' in source and 'ar_saturn' in source,
    'celestial_shared_position': 'self.physical_moon_root.setPos(self.render,sky_pos)' in source and 'self.ar_saturn_root.setPos(self.render,sky_pos)' in source,
    'celestial_world_fixed_anchor': 'World-space celestial anchor' in source and 'camera_pos+direction' not in source and 'moon_world_fixed=1' in source,
    'sun_world_fixed_anchor': 'sun_world_fixed=1' in source and 'pos=Vec3(math.sin(az)*horizontal,math.cos(az)*horizontal,math.sin(alt)*distance)' in source,
    'celestial_correct_card_aspect': 'moon_cm.setFrame(-18.0,18.0,-18.0,18.0)' in source and 'sat_cm.setFrame(-48.0,48.0,-48.0,48.0)' in source and 'sun_card' in source and 'setFrame(-24.0,24.0,-24.0,24.0)' in source,
    'celestial_physical_time_authority': 'h=float(self.physical_time_hours)%24.0' in source,
    'celestial_horizon_fade': 'horizon_fade=self._smoothstep01' in source,
    'celestial_camera_masks': 'self.physical_moon_root.hide(AR_CAMERA_MASK)' in source and 'self.ar_saturn_root.hide(NORMAL_CAMERA_MASK)' in source,
    'celestial_smoke_support': 'CELESTIAL_SMOKE_PASS' in source and 'args.celestial_smoke' in source,
    'outer_world_qa': '"outer_world":' in source and 'lens_outer_world' in source,
    'celestial_qa': '"celestial":' in source and 'lens_celestial' in source,
    'outer_detail_stats': all(token in source for token in ('outer_trees','outer_shrubs','outer_shore_breakup')),
    'outer_detail_builder': 'def _build_outer_world_details' in source and 'outer_shore_breakup_' in source and 'outer_shrub_' in source,
    'tree_builders_removed': 'def _make_outer_tree' not in source and 'def _make_tree' not in source,
    'tree_collision_removed': 'def _make_outer_tree' not in source and 'def _make_tree' not in source and 'self._make_outer_tree(' not in source and 'self._make_tree(' not in source,
    'outer_bridge_corridors': 'radius < 970.0' in source and '(0,90,180,270)' in source,
    'natural_sun_builder': 'def _build_sky_depth_system' in source and 'physical_sun' in source and 'ar_natural_sun' in source,
    'sun_shared_position': 'self.physical_sun_root.setPos(self.render,pos); self.ar_natural_sun_root.setPos(self.render,pos)' in source,
    'sun_geographic_fade': 'alpha*outer_mix' in source and 'ar_natural_sun_root.setColorScale' in source,
    'cloud_cluster_count': 'for idx in range(24)' in source and 'cloud_layers"] = 48' in source,
    'cloud_weather_response': 'cloud_cover=max' in source and 'cloud_dark=max' in source and 'storm_alpha>clear_alpha+0.5' in source,
    'cloud_rejected_sheet_absent': 'natural_cloud_layer' not in source,
    'physical_water_shader': 'def _configure_physical_water_shader' in source and 'water.setShader(self.physical_water_shader)' in source,
    'physical_water_no_displacement': 'gl_Position=p3d_ModelViewProjectionMatrix*p3d_Vertex' in source and 'water_roughness' in source,
    'physical_water_sky_reflection': 'sky_reflection' in source and 'fres=pow' in source,
    'physical_water_celestial_glints': 'sun_reflection' in source and 'moon_reflection' in source and 'sun_alpha' in source and 'moon_alpha' in source,
    'physical_water_weather_response': 'rough=max(0.12,min(1.0,0.15+0.56*rain+0.22*(1.0-sun_gain)))' in source,
    'physical_water_smoke_support': 'WATER_SMOKE_PASS' in source and 'args.water_smoke' in source,
    'citizen_orb_constants': 'CITIZEN_ORB_MAX_RADIUS = 468.0' in source and 'CITIZEN_ORB_TOTAL = 20' in source,
    'citizen_orb_builder': 'def _build_citizen_presence_orbs' in source and 'self._build_citizen_presence_orbs()' in source,
    'citizen_orb_update': 'def _update_citizen_presence_orbs' in source and 'self._update_citizen_presence_orbs()' in source,
    'citizen_orb_ar_only': 'self.utopia_root.hide(NORMAL_CAMERA_MASK)' in source and 'citizen_core_' in source,
    'citizen_orb_sparse_population': 'CITIZEN_ORB_TOTAL = 20' in source and 'for district,center in centers.items()' in source,
    'citizen_orb_commuters': 'mode=="commuter"' in source and 'citizen_commuter_' in source,
    'citizen_orb_wall_clamp': 'min(CITIZEN_ORB_MAX_RADIUS,float(radius))' in source,
    'citizen_orb_no_collision_contract': 'no_collision=all' in source and 'collision=0' in source,
    'citizen_orb_smoke_support': 'CITIZEN_ORBS_SMOKE_PASS' in source and 'args.citizen_orbs_smoke' in source,
    'citizen_orb_qa_state': '"citizens":' in source and 'lens_citizens' in source,
    'district_music_config': (root / 'audio' / 'music' / 'district_music.json').exists(),
    'district_music_guide': (root / 'audio' / 'music' / 'README.md').exists(),
    'district_music_loader': 'def _load_district_music' in source and 'loadSfx' in source,
    'district_music_shared_sfx_owner': 'same explicitly activated SFX/OpenAL owner' in source and 'self.district_music = {}' in source,
    'district_music_crossfade': 'def _district_music_weights' in source and 'boundary_crossfade=1' in source,
    'district_music_exterior_fade': 'music_outer_fade_start' in source and 'outer_silent_radius' in source,
    'district_music_update': 'self._update_district_music(dt)' in source,
    'district_music_stop': 'self._stop_district_music()' in source,
    'district_music_smoke': 'DISTRICT_MUSIC_SMOKE_PASS' in source and 'args.music_smoke' in source,
    'district_music_replaceable_assets': all((root / 'audio' / 'music' / name).exists() for name in (
        'core_unity_forum.wav','north_corporate_terrace.wav','east_innovation_pulse.wav','south_mirage_promenade.wav','west_foundry_works.wav')),
    'public_interior_builder': 'def _build_public_interiors' in source and 'self._build_public_interiors()' in source,
    'public_interior_five_districts': all(token in source for token in ('Unity Civic Reception','Archive Public Lobby','Innovation Demonstration Lab','Mirage Public Lounge','Foundry Public Workshop')),
    'public_interior_real_collision': 'def _interior_physical_box' in source and 'self._add_box_collision(np, sx, sy, sz)' in source,
    'public_interior_open_door_contract': 'door_w = 4.2' in source and 'traversable=5' in source,
    'public_interior_ar_overlay': 'def _interior_ar_box' in source and 'interior_{theme_key}_ar_floor' in source,
    'public_interior_local_lighting': 'PointLight' in source and 'interior_{theme_key}_light' in source,
    'public_interior_district_props': all(token in source for token in ('archive_shelf_','lab_demo_plinth_','lounge_bench_','workshop_bench_','core_reception_desk_')),
    'public_interior_smoke': 'INTERIORS_SMOKE_PASS' in source and 'args.interiors_smoke' in source,
    'public_interior_qa': 'interior_core' in source and 'lens_interior_west' in source,
    'surface_authority_helper': 'def _is_walkable_surface_xy' in source and 'WATER_SURFACE_PLAYER_Z' in source,
    'water_not_flat_ground': 'return 0.0 if self._is_walkable_surface_xy(x,y) else WATER_SURFACE_PLAYER_Z' in source,
    'swim_speed_authority': 'SWIM_SPEED = 2.8' in source and 'not self.in_water' in source,
    'surface_smoke_support': 'SURFACE_SMOKE_PASS' in source and 'args.surface_smoke' in source,
    'horizontal_disc_front_winding': 'prim.addVertices(0,1+((i+1)%segments),1+i)' in source,
    'horizontal_annulus_front_winding': source.count('prim.addVertices(a,d,b); prim.addVertices(a,c,d)') >= 2,
    'surface_winding_regression_gate': 'top_face_winding=1' in source and 'first_triangle_signed_z' in source,
    'transit_avenue_support_split': 'if i%8==0:' in source and 'add_support(angle-step_angle' in source and 'add_support(angle+step_angle' in source,
    'transit_support_registry': 'self.transit_support_positions=[]' in source and 'self.transit_support_positions.append' in source,
    'traversal_smoke_support': 'TRAVERSAL_SMOKE_PASS' in source and 'args.traversal_smoke' in source,
    'transit_clearance_contract': 'transit_support_clearance=1' in source and 'support_min' in source,
    'developer_tour_controls_gated': 'if getattr(self.args,"dev_controls",False):' in source and 'ap.add_argument("--dev-controls"' in source,
    'permanent_hud_hidden': 'self.hud_title.hide()' in source and 'No permanent explanatory HUD' in source,
    'pause_audio_attenuation': source.count('pause_gain=0.28 if self.paused else 1.0') >= 2,
    'pause_audio_smoke': 'AUDIO_STATE_SMOKE_PASS' in source and 'args.audio_state_smoke' in source,
    'interior_scoped_ambient_fill': 'AmbientLight(f"interior_{theme_key}_ambient")' in source and 'ambient_lights' in source,
    'interior_three_fixture_lights': 'for lx in (-5.1,0.0,5.1):' in source,
    'qa_resolution_override': 'ap.add_argument("--width",type=int)' in source and 'ap.add_argument("--height",type=int)' in source,
    'window_title_uses_version': 'window-title {APP_NAME} // {VERSION}' in source,
    'gleebs_bam_asset': (root / 'assets' / 'characters' / 'gleebs' / 'Gleebs_Game.bam').exists(),
    'gleebs_actor_import': 'from direct.actor.Actor import Actor' in source and 'Actor(Filename.fromOsSpecific(str(bam_path)))' in source,
    'gleebs_physical_builder': 'def _build_gleebs_physical_import' in source and 'self._build_gleebs_physical_import()' in source,
    'gleebs_required_clips': '{\"Idle\", \"Walk\"}.issubset(anims)' in source,
    'gleebs_split_representation': 'root.hide(AR_CAMERA_MASK)' in source and 'gleebs_ar_root' in source and 'root.hide(NORMAL_CAMERA_MASK)' in source,
    'gleebs_gate_placement': 'GLEEBS_POSITION = (2.8, -512.5, 0.0)' in source,
    'gleebs_body_collision': 'CollisionTube(0,0,0.08, 0,0,GLEEBS_COLLISION_HEIGHT, GLEEBS_COLLISION_RADIUS)' in source,
    'gleebs_idle_loop': 'actor.loop(\"Idle\")' in source,
    'gleebs_smoke_support': 'GLEEBS_SMOKE_PASS' in source and 'args.gleebs_smoke' in source,
    'gleebs_physical_wear': 'def _tune_gleebs_physical_damaged_materials' in source and 'depleted and unhealthy' in source and 'Uneven wear by material' in source,
    'gleebs_ar_double_scale': 'GLEEBS_AR_SCALE = GLEEBS_SCALE * 2.0' in source and 'root.setScale(GLEEBS_AR_SCALE)' in source and 'ar_ratio=2.0' in source,
    'gleebs_split_contact_shadows': 'gleebs_ar_contact_shadow' in source and 'self.gleebs_shadow_card.hide(AR_CAMERA_MASK)' in source and 'self.gleebs_ar_shadow_card.hide(NORMAL_CAMERA_MASK)' in source,
    'ar_gate_apron_coverage': 'gate_apron_' in source and 'apron_mid=507.5' in source and 'gate_aprons=4' in source,
    'gleebs_qa_state': '\"gleebs\":' in source and 'lens_gleebs' in source,
    'cardinal_gate_road_continuity': '515 if angle%90==0 else 500' in source,
    'fixed_gameplay_aspect': 'GAMEPLAY_ASPECT = 16.0 / 9.0' in source and 'lens.setAspectRatio(GAMEPLAY_ASPECT)' in source,
    'fixed_display_region': 'def _apply_gameplay_viewport' in source and 'setDimensions(*dims)' in source,
    'viewport_ui_alignment': 'for camera_np in (getattr(self,"cam",None),getattr(self,"cam2d",None),getattr(self,"cam2dp",None))' in source,
    'viewport_resize_event': 'self.accept("window-event", self._on_window_event)' in source,
    'viewport_smoke_support': 'VIEWPORT_SMOKE_PASS' in source and 'args.viewport_smoke' in source,
    'gleebs_uniform_upscale': 'GLEEBS_SCALE = 1.12' in source and 'root.setScale(GLEEBS_SCALE)' in source,
    'gleebs_ar_builder': 'def _build_gleebs_ar_presentation' in source and 'self._build_gleebs_ar_presentation()' in source,
    'gleebs_ar_material_finish': 'def _tune_gleebs_ar_materials' in source and 'setSpecular' in source and 'setShininess' in source,
    'gleebs_eye_glow': 'def _build_gleebs_eye_glow' in source and 'gleebs_ar_eye_light' in source and 'eye_glow_card_' in source,
    'projected_shadow_builder': 'def _build_projected_shadows' in source and 'gleebs_contact_shadow' in source,
    'projected_shadow_time_weather': 'sun_gain=float(weather["sun_gain"])' in source and 'sun_alt>0.02' in source,
    'gleebs_opening_walk': 'GLEEBS_APPROACH_SPEED = 3.2' in source and 'def _update_gleebs_behavior' in source and 'self._set_gleebs_animation("Walk")' in source,
    'gleebs_idle_head_follow': 'controlJoint(None,"modelRoot","mixamorig:Head")' in source and 'def _update_gleebs_head_tracking' in source,
    'gleebs_spark_system': 'def _build_gleebs_spark_system' in source and 'GLEEBS_SPARK_INTERVAL_MIN = 6.5' in source and 'spark_events' in source,
    'gleebs_radial_audio_config': (root / 'audio' / 'characters' / 'gleebs' / 'gleebs_audio.json').exists(),
    'gleebs_purr_asset': (root / 'audio' / 'characters' / 'gleebs' / 'gleebs_purr.wav').exists(),
    'gleebs_spark_asset': (root / 'audio' / 'characters' / 'gleebs' / 'gleebs_spark.wav').exists(),
    'gleebs_audio3d_owner': 'Audio3DManager.Audio3DManager' in source and 'attachSoundToObject(sound,self.gleebs_root)' in source,
    'physical_mist_system': 'def _build_physical_mist_system' in source and 'physical_mist_wisp.png' in source and 'self.physical_mist_root.hide(AR_CAMERA_MASK)' in source,
    'weather_fog_ranges': '"storm":(340.0,950.0)' in source and 'self.world_fog.setLinearRange(onset,opaque)' in source,
    'ar_pink_clouds': 'ar_cloud_rgb=self._lerp_tuple((0.42,0.10,0.34),(1.00,0.36,0.66)' in source,
    'ar_planet_shading': 'vec3 N=normalize' in source and 'float bands=' in source and 'ringBands' in source,
    'gleebs_behavior_smoke_support': 'GLEEBS_BEHAVIOR_SMOKE_PASS' in source and 'args.gleebs_behavior_smoke' in source,
    'gleebs_audio_smoke_support': 'GLEEBS_AUDIO_SMOKE_PASS' in source and 'args.gleebs_audio_smoke' in source,
    'atmosphere_smoke_support': 'ATMOSPHERE_SMOKE_PASS' in source and 'args.atmosphere_smoke' in source,
    'shadow_smoke_support': 'SHADOW_SMOKE_PASS' in source and 'args.shadow_smoke' in source,
    'global_shadow_categories': all(token in source for token in ('"buildings"','"walls"','"bridges"','"trees"','"interiors"')) and 'SHADOW_ACTIVE_RADIUS = 320.0' in source and 'def _build_projected_shadows' in source,
    'shadow_surface_authority': 'def _shadow_surface_z' in source and 'return 0.135' in source and 'self._shadow_surface_z' in source,
    'explicit_horizontal_shadow_geometry': 'Horizontal XY shadow quad' in source and 'GeomVertexFormat.getV3t2()' in source,
    'physical_surface_detail_builder': 'def _configure_physical_surface_materials' in source and all((root / 'assets' / 'textures' / 'physical' / name).exists() for name in ('asphalt_detail.png','concrete_detail.png','grass_detail.png','dirt_detail.png')),
    'gleebs_live_stop_radius': 'max_safe=max(0.0,player_dist-GLEEBS_APPROACH_STOP_DISTANCE)' in source and 'GLEEBS_APPROACH_STOP_DISTANCE = 2.6' in source,
    'gleebs_wave_state': 'def _start_gleebs_wave' in source and 'def _apply_gleebs_wave_pose' in source and 'GLEEBS_WAVE_SECONDS = 2.4' in source,
    'windows_openal_backend': 'audio-library-name p3openal_audio' in source and 'enableSoundEffects(True)' in source and 'enableMusic(True)' in source,
    'shared_sfx_loop_owner': 'self.loader.loadSfx' in source and 'Audio3DManager.Audio3DManager' in source,
    'ar_static_batching': 'def _optimize_ar_scene_graph' in source and 'flattenStrong()' in source and '_ar_static_batch' in source,
    'ar_activity_distance_culling': 'AR_ACTIVITY_DRAW_RADIUS = 340.0' in source and 'def _update_ar_activity_visibility' in source,
    'ar_updates_gated': 'ar_active=hasattr(self,"ar_buffer") and self.ar_buffer.isActive()' in source,
    'ar_optimization_smoke': 'AR_OPTIMIZATION_SMOKE_PASS' in source and 'args.ar_optimization_smoke' in source,
    'gleebs_wave_joint_release': 'def _release_gleebs_wave_controls' in source and 'actor.releaseJoint("modelRoot",joint)' in source and 'wave_joint_released' in source,
    'startup_1080p_standard': source.count('args.width or 1920') >= 2 and source.count('args.height or 1080') >= 2,
    'readme_pass59_identity': 'Utopia Lens Tour — Pass 59' in (root / 'README.md').read_text(encoding='utf-8'),
    'authority_pass59_identity': 'Pass 59 Design Authority' in (root / 'DESIGN_AUTHORITY.md').read_text(encoding='utf-8'),
    'report_pass59_identity': (root / 'Utopia_Lens_Tour_Pass59_REPORT.md').exists() and 'Pass 59 Report' in (root / 'Utopia_Lens_Tour_Pass59_REPORT.md').read_text(encoding='utf-8'),
    'human_resident_specs': 'HUMAN_RESIDENT_SPECS' in source and 'Resident_Male' in source and 'Resident_Female' in source,
    'resident_idle_variation_update': '_update_human_resident_idle_variation' in source,
    'resident_smoke_support': '--resident-smoke' in source and 'RESIDENT_SMOKE_PASS' in source,
    'resident_physical_ar_split': '_build_human_residents_physical' in source and '_build_human_residents_ar' in source,
    'resident_neon_skeleton_binding': '_build_resident_ar_design' in source and '_resident_joint' in source and 'wrtReparentTo(parent_joint)' in source,
    'resident_deterministic_neon': 'neon_seed' in source and 'random.Random(int(neon_seed))' in source and 'deterministic_neon=1' in source,
    'resident_neon_follow_smoke': 'bone_follow=1' in source and 'ar_accent_meta' in source,
    'ar_park_surface_coverage': 'ar_park_{angle}' in source and 'park_surfaces' in source and 'physical_hidden_from_ar=1' in source,
    'ar_textured_node_pads': 'textured_node_pads' in source and 'promenade_node_{angle}_{i}' in source and '_promenade_textured_box' in source,
    'tree_runtime_removal_contract': 'trees_removed=1' in source and 'outer_trees' in source and 'tree_free=' in source,
    'ar_coverage_smoke_support': 'AR_COVERAGE_SMOKE_PASS' in source and 'args.ar_coverage_smoke' in source,
    'public_interior_ar_exterior_coverage': 'ar_exterior_shells' in source and 'ar_exterior_patterned' in source and 'interior_{theme_key}_ar_exterior_side' in source and 'interior_{theme_key}_ar_exterior_front' in source,
    'public_interior_ar_exterior_smoke': 'ar_exterior_shells=' in source and 'ar_exterior_patterned=' in source and 'ar_exterior_ok' in source,
}
print(json.dumps(checks, indent=2))
failed = [k for k, v in checks.items() if not v]
if failed:
    raise SystemExit('FAIL ' + ','.join(failed))
print(f'STATIC_VALIDATION_PASS {len(checks)}/{len(checks)}')
