from __future__ import annotations

PROJECT_NAME = "GHOST SIGNAL: UTOPIA"
PASS_ID = "22"
VERSION = "1.0.0-rc3"
BUILD_LABEL = "CHAPTER ONE V1 RELEASE CANDIDATE 3"
WINDOW_CAPTION = f"{PROJECT_NAME} — {BUILD_LABEL}"
